USE [DBAdmin]

GO

CREATE CLUSTERED INDEX [PK_Query_CreationTime] ON [dba].[query]
(
	[creationtime] ASC
)WITH (PAD_INDEX = ON, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, 
ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, 
FILLFACTOR = 80) 
ON [DATA]

GO


